"""
AI Summary Route — Generates executive summaries using OpenAI API.
Falls back to template-based summaries when API key is not configured.
"""

import os
from fastapi import APIRouter
from app.database import execute_query

router = APIRouter()


def get_analytics_context() -> dict:
    """Fetch current analytics data for AI summary context."""
    kpis = execute_query("SELECT * FROM v_kpi_summary", fetch_all=False)
    categories = execute_query("SELECT * FROM v_threat_category_stats LIMIT 5")
    event_types = execute_query("SELECT * FROM v_event_type_analysis LIMIT 5")

    return {
        "kpis": kpis or {},
        "top_categories": categories,
        "top_event_types": event_types,
    }


def generate_fallback_summary(context: dict) -> dict:
    """Generate a template-based executive summary when OpenAI is unavailable."""
    kpis = context.get("kpis", {})
    categories = context.get("top_categories", [])
    event_types = context.get("top_event_types", [])

    total = kpis.get("total_events", 0)
    critical = kpis.get("critical_events", 0)
    high = kpis.get("high_events", 0)
    unique_ips = kpis.get("unique_source_ips", 0)
    avg_sev = kpis.get("avg_severity_score", 0)
    if hasattr(avg_sev, '__float__'):
        avg_sev = float(avg_sev)

    top_cat = categories[0]["threat_category"] if categories else "N/A"
    top_cat_count = categories[0]["event_count"] if categories else 0
    top_event = event_types[0]["event_type"] if event_types else "N/A"

    critical_pct = (critical / total * 100) if total > 0 else 0
    high_pct = (high / total * 100) if total > 0 else 0

    summary = f"""## Executive Security Intelligence Summary

### Threat Landscape Overview
The platform has analyzed **{total:,}** security events originating from **{unique_ips:,}** unique source IP addresses. The average severity score across all events is **{avg_sev:.1f}/10**, indicating a {'heightened' if avg_sev > 5 else 'moderate'} overall threat level.

### Critical Findings
- **{critical:,}** critical-severity events detected ({critical_pct:.1f}% of total), requiring immediate attention
- **{high:,}** high-severity events ({high_pct:.1f}% of total) warrant priority investigation
- The most prevalent threat category is **{top_cat.replace('_', ' ').title()}** with {top_cat_count:,} events
- The most common event type is **{top_event.replace('_', ' ').title()}**

### Risk Assessment
{'🔴 **HIGH RISK**: Critical events exceed 10% of total traffic. Immediate escalation recommended.' if critical_pct > 10 else '🟡 **MODERATE RISK**: Critical events are within expected thresholds, but continued monitoring is advised.' if critical_pct > 5 else '🟢 **STANDARD RISK**: Security posture is within normal parameters.'}

### Recommendations
1. **Prioritize** investigation of the {critical:,} critical-severity events
2. **Enhance** monitoring for {top_cat.replace('_', ' ')} attack patterns
3. **Review** access controls for the {unique_ips:,} unique source IPs flagged
4. **Implement** automated response rules for recurring {top_event.replace('_', ' ')} incidents
5. **Schedule** a threat hunting exercise focused on the top attack categories

---
*Generated by Security Intelligence Platform — Automated Analysis Engine*
"""

    return {
        "summary": summary,
        "source": "template",
        "model": "built-in",
        "context": {
            "total_events": total,
            "critical_events": critical,
            "high_events": high,
            "unique_sources": unique_ips,
            "avg_severity": round(avg_sev, 2) if isinstance(avg_sev, float) else avg_sev,
        },
    }


async def generate_openai_summary(context: dict, api_key: str) -> dict:
    """Generate an executive summary using OpenAI API."""
    from openai import OpenAI

    client = OpenAI(api_key=api_key)

    kpis = context.get("kpis", {})
    categories = context.get("top_categories", [])
    event_types = context.get("top_event_types", [])

    # Serialize for prompt
    def safe_val(v):
        if hasattr(v, '__float__'):
            return float(v)
        if hasattr(v, 'packed'):
            return str(v)
        return v

    kpi_str = ", ".join(f"{k}: {safe_val(v)}" for k, v in kpis.items()) if kpis else "No data"
    cat_str = ", ".join(
        f"{c.get('threat_category', 'N/A')} ({c.get('event_count', 0)} events)"
        for c in categories[:5]
    )
    evt_str = ", ".join(
        f"{e.get('event_type', 'N/A')} ({e.get('total_count', 0)} events)"
        for e in event_types[:5]
    )

    prompt = f"""You are a senior cybersecurity analyst. Generate an executive security intelligence summary based on the following data:

KPI Metrics: {kpi_str}

Top Threat Categories: {cat_str}

Top Event Types: {evt_str}

Provide:
1. A threat landscape overview
2. Critical findings with specific numbers
3. Risk assessment (HIGH/MODERATE/STANDARD)
4. Actionable recommendations (5 items)

Format in Markdown with headers. Be specific with numbers. Keep it professional and concise."""

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You are a cybersecurity intelligence analyst producing executive summaries."},
            {"role": "user", "content": prompt},
        ],
        max_tokens=1000,
        temperature=0.3,
    )

    return {
        "summary": response.choices[0].message.content,
        "source": "openai",
        "model": "gpt-4o-mini",
        "usage": {
            "prompt_tokens": response.usage.prompt_tokens,
            "completion_tokens": response.usage.completion_tokens,
        },
    }


@router.get("/summary")
async def get_ai_summary():
    """Generate AI-powered executive security summary."""
    context = get_analytics_context()
    api_key = os.getenv("OPENAI_API_KEY", "").strip()

    if api_key:
        try:
            result = await generate_openai_summary(context, api_key)
            return result
        except Exception as e:
            # Fall back to template if OpenAI fails
            result = generate_fallback_summary(context)
            result["fallback_reason"] = f"OpenAI API error: {str(e)}"
            return result
    else:
        result = generate_fallback_summary(context)
        result["fallback_reason"] = "OPENAI_API_KEY not configured"
        return result
